spring.application.name=reto-tecnico


service.external.gorest.url=https://gorest.co.in/public/v2

logging.level.com.aarteaga.reto_tecnico.feign= DEBUG
#logging.level.feign=DEBUG
#logging.level.feign.Logger=DEBUG

#feign.client.config.default.loggerLevel= BASIC ///version menor a 3.X in springboot
#feign.client.config.testClient.loggerLevel= BASIC ///version menor a 3.X in springboot
#feign.client.config.usuarioClient.loggerLevel= NONE ///version menor a 3.X in springboot

#spring.cloud.openfeign.client.config.usuarioClient.loggerLevel= none
#spring.cloud.openfeign.client.config.usuarioClient.loggerLevel= basic
#spring.cloud.openfeign.client.config.default.logger= CustomFeignRequestLogging



